set_global_assignment -name SOURCE_FILE ../../fpu//rtl/scoore_fpu.h
set_global_assignment -name SOURCE_FILE ../../fpu//rtl/dfunc.h
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/stage_flop_retry.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_divider_selector_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/scoore_fpu.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_propagate_nan_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/stage.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/register.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_div64_to_64.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_lead0.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_divide_result_selector_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_propagate_div.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_sqrt64.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_div64_post_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_sqrt64_post_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_mult64.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_div64.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_mult64_post_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_add64_post_comb.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_op_predec.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_add64.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_result_queue.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_normalize_fp.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_ex.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_denorm.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fp_normalize.v -hdl_version "SystemVerilog_2005"
set_global_assignment -name VERILOG_FILE ../../fpu//rtl/fpu.v -hdl_version "SystemVerilog_2005"

set_global_assignment -name SEARCH_PATH "../../fpu"
