verilog_defaults -add -I../../mor1kx/rtl/verilog/

read_verilog ../../mor1kx/rtl/verilog/mor1kx-defines.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_dmmu.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_pic.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_rf_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_icache.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cpu_prontoespresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_branch_prediction.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_ctrl_prontoespresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cache_lru.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cpu.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_execute_alu.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_decode_execute_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_ticktimer.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_rf_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_fetch_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_decode.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx-sprs.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_top.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_f2i.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_addsub.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_cmp.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_i2f.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_muldiv.v
read_verilog ../../mor1kx/rtl/verilog/pfpu32/pfpu32_rnd.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_lsu_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_dcache.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_true_dpram_sclk.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_wb_mux_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_ctrl_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_fetch_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cfgrs.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_ctrl_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_wb_mux_cappuccino.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_fetch_prontoespresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_bus_if_wb32.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_immu.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_store_buffer.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_lsu_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_branch_predictor_simple.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cpu_espresso.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_simple_dpram_sclk.v
read_verilog ../../mor1kx/rtl/verilog/mor1kx_cpu_cappuccino.v

